name: CI_EIOPS

on: [push]

jobs:
  eiops_CI:
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v1
      - name: Running eiops script one line
        run: echo Hello, world $(hostname)!
      - name: Running eiops script multiline
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo "BotecoUnix | EIOPS"

  eiops_Fortify:
      runs-on: ubuntu-latest
      needs: eiops_CI

      steps:
      - uses: actions/checkout@v1
      - name: Running validate Fortify
        run: |
          echo "Listing Files : $(ls -la)"
          echo $(date)
  
  eiops_Sonar:
      runs-on: ubuntu-latest
      needs: eiops_Fortify

      steps:
      - uses: actions/checkout@v1
      - name: Final build status indicator
        if: success()
        run: | 
          echo "Sucesso total, desce a cerveja e o churras..."
          curl -I https://fusionhelp.oracle.com
        
      - name: Final build status indicator
        if: failure()
        run: | 
          echo "
          Falha na matrix do boteco
          Calling Jose Renato
          "
  
  eiops_BuildPublish:
      runs-on: ubuntu-latest
      needs: 
        - eiops_Fortify
        - eiops_Sonar

      steps:
      - uses: actions/checkout@v1
      - name: Running CD Process
        run: |
          echo "Initialize Build App..."
          sleep 3
          echo "Build Completed!"
      - name: Running publish package
        run: |
          echo Publish package
          echo "BotecoUnix | EIOPS"
        